package scanner

var SecretPatterns = map[string]string{
	"AWS Access Key":      `AKIA[0-9A-Z]{16}`,
	"AWS Secret Key":      `(?i)aws.{0,30}secret.{0,30}['\"][0-9a-zA-Z/+]{40}['\"]`,
	"AWS MWS Auth Token":  `amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`,
	"AWS Session Token":   `(?i)aws_session_token(?:[=:\"\']){1,3}([a-zA-Z0-9/+=]{16,})`,
	"GitHub PAT":          `gh[pousr]_[A-Za-z0-9_]{36,}`,
	"GitHub Fine-grained": `github_pat_[A-Za-z0-9_]{82}`,
	"GitHub OAuth":        `gho_[a-zA-Z0-9]{36}`,
	"GitLab PAT":          `glpat-[A-Za-z0-9_\-]{20}`,
	"Bitbucket Client ID": `client_id=[a-zA-Z0-9]{32}`,
	"Bitbucket Secret":    `client_secret=[a-zA-Z0-9_\-]{64}`,
	"Google API Key":      `AIza[0-9A-Za-z\-_]{35}`,
	"Google Cloud Key":    `GOOG[\w\W]{10,30}`,
	"Google OAuth":        `ya29\.[0-9A-Za-z\-_]+`,
	"Slack Token":         `xox[baprs]-[0-9A-Za-z\-]{10,}`,
	"Slack Webhook":       `https://hooks\.slack\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[a-zA-Z0-9]+`,
	"Stripe Standard Key": `(?:sk|pk)_(test|live)_[0-9a-zA-Z]{24,}`,
	"Stripe Restricted":   `rk_(test|live)_[0-9a-zA-Z]{24,}`,
	"Square Access Token": `EAAA[a-zA-Z0-9]{60}`,
	"Square OAuth":        `sq0[a-z]{3}-[0-9A-Za-z\-_]{22,43}`,
	"PayPal Client ID":    `Ad-[a-zA-Z0-9]{16,}`,
	"PayPal Secret":       `E[a-zA-Z0-9_-]{16,}`,
	"SendGrid Key":        `SG\.[a-zA-Z0-9_\-]{22}\.[a-zA-Z0-9_\-]{43}`,
	"Mailgun Key":         `key-[0-9a-zA-Z]{32}`,
	"Mailgun Pub Key":     `pubkey-[0-9a-zA-Z]{32}`,
	"Mailchimp Key":       `[0-9a-f]{32}-us[0-9]{1,2}`,
	"Twilio Account SID":  `AC[a-zA-Z0-9]{32}`,
	"Twilio Auth Token":   `(?i)twilio.{0,20}['\"][a-f0-9]{32}['\"]`,
	"Twilio API Key":      `SK[0-9a-fA-F]{32}`,
	"Telegram Bot Token":  `[0-9]{8,10}:[a-zA-Z0-9_\-]{35}`,
	"Discord Bot Token":   `([NMO][a-zA-Z0-9_-]{23,27}\.[a-zA-Z0-9_-]{6}\.[a-zA-Z0-9_-]{27})`,
	"Discord Webhook":     `https://discord\.com/api/webhooks/[0-9]+/[a-zA-Z0-9_-]+`,
	"Azure Client Secret": `(?i)client.?secret.{0,20}['\"][a-zA-Z0-9~_\-.]{34,}['\"]`,
	"Azure Storage Key":   `DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/=]{88}`,
	"Azure Tenant ID":     `tenant(?:_id|Id)?(?:[\s=:\'\"]+)([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})`,
	"Heroku API Key":      `[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}`,
	"DigitalOcean Token":  `dop_v1_[a-f0-9]{64}`,
	"Pulumi Token":        `pul-[a-f0-9]{40}`,
	"Vercel Token":        `[\s=:\'\"]([A-Za-z0-9_\-]{24})[\s=:\'\"]`,
	"Datadog Token":       `ddp_[a-zA-Z0-9_\-]{32}`,
	"New Relic Key":       `(?i)NRRA-[a-fA-F0-9]{27}`,
	"Sentry Token":        `sntrys_[a-zA-Z0-9_\-]{64}`,
	"Grafana Token":       `glc_[A-Za-z0-9+/]{32,}`,
	"PagerDuty Token":     `pd-[A-Za-z0-9_\-]{20}`,
	"Algolia API Key":     `(?i)algolia.{0,20}['\"][a-zA-Z0-9]{32}['\"]`,
	"Artifactory Token":   `(?:\s|=|:|\"|\^)AKC[a-zA-Z0-9]{10,}`,
	"Asana Token":         `0\/[0-9a-fA-F]{32}`,
	"Auth0 Token":         `auth0(?:\||[a-zA-Z0-9_\-]{32})`,
	"Calendly Token":      `eyJhb[a-zA-Z0-9_\-]{20,}`,
	"CircleCI Token":      `(?i)circleci.{0,20}['\"][a-f0-9]{40}['\"]`,
	"Databricks Token":    `dapi[a-f0-9]{32}`,
	"Dropbox Token":       `sl\.[a-zA-Z0-9_\-]{15,}`,
	"Figma Token":         `figd_[a-zA-Z0-9\-_]{39}`,
	"HubSpot Token":       `pat-[a-z]{2}-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}`,
	"Intercom Token":      `dG9r:[a-zA-Z0-9_\-]{20,}`,
	"Kraken Key":          `[A-Za-z0-9_\-]{80,90}`,
	"Linear API Key":      `lin_api_[a-zA-Z0-9]{40}`,
	"LinkedIn ID":         `(?i)linkedin(?:_client)?_id(?:[\s=:\'\"]+)([a-zA-Z0-9]{14})`,
	"Mapbox Token":        `pk\.eyJ1[a-zA-Z0-9_\-\.]+`,
	"Notion Token":        `secret_[a-zA-Z0-9]{43}`,
	"NPM Token":           `npm_[A-Za-z0-9]{36}`,
	"OpenAI API Key":      `sk-[a-zA-Z0-9]{48}`,
	"Plaid Client ID":     `client_id(?:[\s=:\'\"]+)([a-f0-9]{24})`,
	"Plaid Secret":        `secret(?:[\s=:\'\"]+)([a-f0-9]{30})`,
	"Postman API Key":     `PMAK-[a-fA-F0-9]{24}-[a-fA-F0-9]{34}`,
	"RubyGems Token":      `rubygems_[a-f0-9]{48}`,
	"Salesforce Token":    `(?i)salesforce.{0,20}['\"][0-9A-Za-z!@#$%^&*()_+]{40,80}['\"]`,
	"Shopify Token":       `shpat_[a-fA-F0-9]{32}`,
	"Spotify Secret":      `(?i)spotify.{0,20}['\"][a-zA-Z0-9]{32}['\"]`,
	"Supabase Token":      `sbp_[a-zA-Z0-9]{40}`,
	"Typeform Token":      `tfp_[a-zA-Z0-9]{40}`,
	"Vault Token":         `hvs\.[a-zA-Z0-9_\-]{90,}`,
	"WPEngine Token":      `['\"]wpe_auth['\"].{0,5}['\"][a-z0-9]{40}['\"]`,
	"Zendesk Token":       `(?i)zendesk.{0,20}['\"][a-zA-Z0-9]{40}['\"]`,
	"Cloudinary URL":      `cloudinary://[0-9]+:[A-Za-z0-9_\-]+@[a-z0-9]+`,
	"Contentful Token":    `(?i)contentful(?:_api)?_key(?:[\s=:\'\"]+)([a-zA-Z0-9\-_]{43})`,
	"Netlify Token":       `(?i)netlify.{0,20}['\"][a-zA-Z0-9\-_]{40,43}['\"]`,
	"JWT Token":           `eyJ[a-zA-Z0-9_\-]+\.eyJ[a-zA-Z0-9_\-]+\.[a-zA-Z0-9_\-]+`,
	"Bearer Token":        `(?i)[Bb]earer\s+[A-Za-z0-9\-_\.]{20,}`,
	"Basic Auth":          `(?i)Basic\s+[A-Za-z0-9+/=]{20,}`,
	"Password in URL":     `[a-zA-Z]{3,10}://[^/\s:@]{3,20}:[^/\s:@]{3,20}@`,
	"Firebase URL":        `https?://[a-z0-9\-]+\.firebaseio\.com`,
	"Internal API URL":    `(?i)https?://(?:api|internal|dev|staging|admin)\.[a-z0-9\-]+\.[a-z]{2,}/`,
	"Private Key Block":   `-----BEGIN\s(?:RSA\s|DSA\s|EC\s)?PRIVATE KEY-----`,
	"SSH RSA Private":     `-----BEGIN OPENSSH PRIVATE KEY-----`,
	"SSH DSA Private":     `-----BEGIN DSA PRIVATE KEY-----`,
	"SSH EC Private":      `-----BEGIN EC PRIVATE KEY-----`,
	"PGP Private Block":   `-----BEGIN PGP PRIVATE KEY BLOCK-----`,
	"Bitcoin Address":     `(?i)(?:bitcoin|btc).{0,20}['\"](1[a-km-zA-HJ-NP-Z1-9]{25,34}|3[a-km-zA-HJ-NP-Z1-9]{25,34}|bc1[q-z0-9]{39,59})['\"]`,
	"Ethereum Address":    `(?i)(?:ethereum|eth).{0,20}['\"](0x[a-fA-F0-9]{40})['\"]`,
	"Generic API Key":     `(?i)(?:api[_\-]?key|apikey|access[_\-]?token|auth[_\-]?token|secret[_\-]?key)['\"\s:=]+([A-Za-z0-9_\-]{20,})`,
	"Generic Secret":      `(?i)(?:secret|password|passwd|pwd)\s*[=:]\s*['\"]([A-Za-z0-9_\-!@#$%^&*]{12,})['\"]`,
	"Generic Client ID":   `(?i)(?:client[_\-]?id|appid)['\"\s:=]+([A-Za-z0-9_\-]{15,})`,
	"Generic Refresh Tok": `(?i)(?:refresh[_\-]?token)['\"\s:=]+([A-Za-z0-9_\-]{20,})`,
	"Generic Bearer Var":  `(?i)(?:bearer|jwt)[_\-]?token['\"\s:=]+([A-Za-z0-9_\-\.]{20,})`,
	"Airtable API Key":    `key[0-9a-zA-Z]{13}`,
	"Amplitude API Key":   `(?i)amplitude.{0,20}['\"][a-f0-9]{32}['\"]`,
	"AppSync API Key":     `da2-[a-z0-9]{26}`,
	"Braintree Token":     `access_token\$[a-z0-9]{5,10}\$[a-z0-9]{30,}`,
	"Buildkite Token":     `bkua_[0-9a-zA-Z]{40}`,
	"ButterCMS Token":     `(?i)butter.{0,20}['\"][0-9a-f]{40}['\"]`,
	"Campfire Token":      `(?i)campfire.{0,20}['\"][a-f0-9]{40}['\"]`,
	"Canny API Key":       `(?i)canny.{0,20}['\"][0-9a-f]{32}['\"]`,
	"Clearbit Key":        `sk_[0-9a-f]{32}`,
	"Coda Token":          `(?i)coda.{0,20}['\"][a-zA-Z0-9_\-]{40,60}['\"]`,
	"Coinbase API Key":    `(?i)coinbase.{0,20}['\"][a-zA-Z0-9_\-]{30,50}['\"]`,
	"Confluent Key":       `(?i)confluent.{0,20}['\"][a-zA-Z0-9]{30,40}['\"]`,
	"Courier API Key":     `pk_[a-z]{4}_[A-Z0-9]{26}`,
	"CustomerIO Key":      `(?i)customerio.{0,20}['\"][0-9a-f]{32}['\"]`,
	"Drip API Key":        `(?i)drip.{0,20}['\"][a-zA-Z0-9_\-]{30,50}['\"]`,
	"Dynatrace Token":     `dt0c01\.[A-Z0-9]{24}\.[A-Z0-9]{64}`,
	"Easypost API Key":    `EZAK[a-zA-Z0-9]{50,}`,
	"Fastly Token":        `(?i)fastly.{0,20}['\"][a-zA-Z0-9_\-]{32}['\"]`,
	"Firebase Cloud Mess": `AAAA[A-Za-z0-9_-]{7}:[A-Za-z0-9_-]{140}`,
	"Flutterwave Key":     `FLWSECK_TEST-[a-h0-9]{32}-X`,
	"Frameio Token":       `fio-u-[a-zA-Z0-9\-_]{64}`,
	"Gitter Token":        `(?i)gitter.{0,20}['\"][a-f0-9]{40}['\"]`,
	"HashiCorp TF Token":  `[a-zA-Z0-9]{14}\.atlasv1\.[a-zA-Z0-9_\-]{60,}`,
	"IronMQ Token":        `(?i)ironmq.{0,20}['\"][a-zA-Z0-9_\-]{30,50}['\"]`,
	"KeenIO API Key":      `(?i)keenio.{0,20}['\"][A-Z0-9]{64}['\"]`,
	"LaunchDarkly Token":  `sdk-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}`,
	"Lokalise Token":      `(?i)lokalise.{0,20}['\"][a-f0-9]{40}['\"]`,
	"MacStadium Token":    `(?i)macstadium.{0,20}['\"][a-zA-Z0-9]{30,50}['\"]`,
	"Mattermost Token":    `(?i)mattermost.{0,20}['\"][a-zA-Z0-9]{26}['\"]`,
	"MessageBird Key":     `(?i)messagebird.{0,20}['\"][a-zA-Z0-9]{25}['\"]`,
	"Mixpanel API Key":    `(?i)mixpanel.{0,20}['\"][a-f0-9]{32}['\"]`,
	"Pendo Token":         `(?i)pendo.{0,20}['\"][a-f0-9]{32}['\"]`,
	"Picqer API Key":      `(?i)picqer.{0,20}['\"][a-zA-Z0-9_\-]{30,50}['\"]`,
	"Ramp Token":          `(?i)ramp.{0,20}['\"][a-zA-Z0-9_\-]{30,50}['\"]`,
	"Sanity API Key":      `sk[a-zA-Z0-9]{40,}`,
	"Scalingo Token":      `tk-[a-zA-Z0-9_\-]{40,}`,
	"Segment API Key":     `(?i)segment.{0,20}['\"][a-zA-Z0-9_\-]{32}['\"]`,
	"Smartling Token":     `(?i)smartling.{0,20}['\"][a-zA-Z0-9_\-]{40}['\"]`,
	"SonarQube Token":     `sq[a-z]{3}_[a-f0-9]{40}`,
	"StackHawk Token":     `hawk\.[a-zA-Z0-9_\-]{20}\.[a-zA-Z0-9_\-]{20}`,
	"TravisCI Token":      `(?i)travis.{0,20}['\"][a-zA-Z0-9_\-]{22}['\"]`,
	"WorkOS API Key":      `sk_[a-zA-Z0-9]{20,}`,
	"Yandex API Key":      `AQVN[A-Za-z0-9_\-]{35,}`,
}

var PatternEntropy = map[string]float64{
	"AWS Access Key":      3.5,
	"AWS MWS Auth Token":  3.0,
	"JWT Token":           3.0,
	"Private Key Block":   2.5,
	"Firebase URL":        2.0,
	"Password in URL":     2.5,
	"Internal API URL":    2.0,
	"Generic API Key":     3.8,
	"Generic Secret":      3.8,
	"Bearer Token":        3.5,
	"Mailchimp Key":       3.0,
}

var DefaultEntropy = 3.0

var FalsePositiveRe = `(?i)^[a-z_\-]+$|^[0-9\.]+$|example\.com|localhost|placeholder|your[_\-]?key|my[_\-]?secret|<[A-Z_]+>|\$\{[A-Z_]+\}|xxx+|test[_\-]key|dummy|changeme|insert[_\-]here|REPLACE_ME|TODO|FIXME|\*{4,}|1234567890|abcdefgh|aaaaaaa|0000000|process\.env\.|window\.__ENV__|__NEXT`
