package scanner

import "strings"

var FalsePositiveRe = `(?i)(application/(json|xml|javascript|x-www-form-urlencoded)|text/(html|plain|xml|javascript)|image/(png|jpeg|gif|svg\+xml)|charset|utf-8|content-type|border-[a-z]+|background-[a-z]+|font-[a-z]+|box-shadow|text-align|margin-[a-z]+|padding-[a-z]+|display:\s*(none|block|inline)|position:\s*(absolute|relative)|index\.js|main\.js|vendor\.js|app\.js|bundle\.js|/api/v\d+/|/oauth/token|/auth/login|/users/|/products/|/api/public|jquery|bootstrap|angular|react|vue|moment|lodash|localhost|127\.0\.0\.1)`

var SecretPatterns = map[string]string{
	// ── Original patterns ─────────────────────────────────────────────────────
	"Google API Key":      `AIza[0-9A-Za-z\-_]{35}`,
	"AWS Access Key":      `AKIA[0-9A-Z]{16}`,
	"AWS Secret Key":      `(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]`,
	"Slack Token":         `xox[baprs]-[0-9]{12}-[0-9]{12}-[0-9a-zA-Z]{24}`,
	"Stripe Standard API": `sk_live_[0-9a-zA-Z]{24}`,
	"Stripe Restricted":   `rk_live_[0-9a-zA-Z]{24}`,
	"GitHub Token":        `ghp_[0-9a-zA-Z]{36}`,
	"Twilio API Key":      `SK[0-9a-fA-F]{32}`,
	"SendGrid API Key":    `SG\.[0-9a-zA-Z_-]{22}\.[0-9a-zA-Z_-]{43}`,
	"Firebase URL":        `.*firebaseio\.com`,
	"RSA Private Key":     `-----BEGIN RSA PRIVATE KEY-----`,

	// ── Banking / PCI ─────────────────────────────────────────────────────────
	"Credit Card (PAN)":         `\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})\b`,
	"IBAN (European format)":    `\b[A-Z]{2}[0-9]{2}(?:[ ]?[0-9a-zA-Z]{4}){4,7}[ ]?[0-9a-zA-Z]{1,2}\b`,
	"Internal IP (10.x.x.x)":    `\b10\.(?:[0-9]{1,3}\.){2}[0-9]{1,3}\b`,
	"Internal IP (192.168.x.x)": `\b192\.168\.[0-9]{1,3}\.[0-9]{1,3}\b`,
	"Internal IP (172.16-31)":   `\b172\.(?:1[6-9]|2[0-9]|3[0-1])\.[0-9]{1,3}\.[0-9]{1,3}\b`,
	"SWIFT / BIC Code":          `\b[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}(?:[A-Z0-9]{3})?\b`,
	"Extended JWT Token":        `\b(?:ey[a-zA-Z0-9_-]{2,}\.ey[a-zA-Z0-9_-]{2,}\.[a-zA-Z0-9_-]{2,})\b`,
	"Azure DB Connection":       `(?i)Server=tcp:[^;]+;Database=[^;]+;User ID=[^;]+;Password=[^;]+;`,
	"AWS ElastiCache Redis":     `(?i)[a-z0-9.-]+\.cache\.amazonaws\.com:[0-9]{4}`,
	"Oracle DB JDBC String":     `(?i)jdbc:oracle:thin:[^:]+/[^@]+@[^:]+:[0-9]+:[a-z0-9]+`,
	"S3 Bucket Leak":            `(?i)[a-z0-9.-]+\.s3\.amazonaws\.com|[a-z0-9.-]+\.s3-[a-z0-9-]+\.amazonaws\.com`,
	"PHP Error Leak":            `(?i)Fatal error:|parse error:|syntax error:|uncaught exception|PDOException`,

	// ── AZ local ──────────────────────────────────────────────────────────────
	"AZ Kapital Bank":             `(?i)(kapital|kapitalbank|kb|birbank)[\w\s-]*[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Umico":                    `(?i)(umico|compet)[\w\s-]*[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ ABB / IBA":                `(?i)(abb|ibar|ibar_az)[\w\s-]*[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Pasha Bank":               `(?i)(pasha|pashabank)[\w\s-]*[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Leobank":                  `(?i)(leobank|leo)[\w\s-]*[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Birmarket":                `(?i)(birmarket)[\w\s-]*[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Payments (Hesab/AsanPay)": `(?i)(hesab_az|asanpay|goldenpay|epul)[\w\s-]*[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Mobile Carriers":          `(?i)(azercell|bakcell|nar)[\w\s-]*api[\w\s-]*[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,

	// ══════════════════════════════════════════════════════════════════════════
	// NEW +500 PATTERNS
	// ══════════════════════════════════════════════════════════════════════════

	// ── Additional cloud / infra keys ─────────────────────────────────────────
	"AWS Session Token":        `(?i)aws_session_token[\w\s]*[:=]\s*['"][A-Za-z0-9\/+=]{100,}['"]`,
	"AWS Gov Access Key":       `AIGA[0-9A-Z]{16}`,
	"AWS IAM Long-term":        `ASIA[0-9A-Z]{16}`,
	"AWS SNS ARN Leak":         `arn:aws:sns:[a-z0-9-]+:[0-9]{12}:[A-Za-z0-9_-]+`,
	"AWS SQS URL Leak":         `https://sqs\.[a-z0-9-]+\.amazonaws\.com/[0-9]{12}/[A-Za-z0-9_-]+`,
	"AWS Lambda ARN":           `arn:aws:lambda:[a-z0-9-]+:[0-9]{12}:function:[A-Za-z0-9_-]+`,
	"AWS DynamoDB Table":       `arn:aws:dynamodb:[a-z0-9-]+:[0-9]{12}:table/[A-Za-z0-9_-]+`,
	"AWS Cognito Pool":         `[a-z]{2}-[a-z]+-[0-9]_[A-Za-z0-9]{9}`,
	"AWS Cognito Client ID":    `(?i)cognito.{0,20}client.{0,10}[:=]\s*['"][0-9a-z]{26}['"]`,
	"GCP Service Account JSON": `(?i)"type":\s*"service_account"`,
	"GCP API Key":              `AIza[0-9A-Za-z\-_]{35}`,
	"GCP OAuth Client ID":      `[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com`,
	"GCP Storage Bucket URL":   `(?i)storage\.googleapis\.com/[a-z0-9._-]+`,
	"Azure Storage Key":        `(?i)DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/=]{88};`,
	"Azure SAS Token":          `(?i)sv=[0-9]{4}-[0-9]{2}-[0-9]{2}&s[sre]=[a-zA-Z0-9%]+&sig=[A-Za-z0-9%/+=]+`,
	"Azure Client Secret":      `(?i)client_secret\s*[:=]\s*['"][A-Za-z0-9~._-]{30,}['"]`,
	"Azure Tenant ID":          `(?i)tenant_?id\s*[:=]\s*['"][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}['"]`,
	"Azure CosmosDB Key":       `(?i)AccountEndpoint=https://[^;]+;AccountKey=[A-Za-z0-9+/=]{88}==;`,
	"Azure Event Hub Conn":     `(?i)Endpoint=sb://[^;]+;SharedAccessKeyName=[^;]+;SharedAccessKey=[A-Za-z0-9+/=]{44};`,
	"DigitalOcean PAT":         `dop_v1_[a-f0-9]{64}`,
	"DigitalOcean OAuth":       `doo_v1_[a-f0-9]{64}`,
	"DigitalOcean Spaces Key":  `(?i)do_spaces.{0,15}[:=]\s*['"][A-Z0-9]{20}['"]`,
	"Heroku API Key":           `(?i)heroku.{0,20}['"][0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}['"]`,
	"Cloudflare API Key":       `(?i)cloudflare.{0,15}[:=]\s*['"][a-zA-Z0-9_-]{40}['"]`,
	"Cloudflare Global Key":    `[0-9a-f]{37}`,
	"Cloudflare CA Key":        `v1\.0-[a-f0-9]{40}-[a-f0-9]{6}`,
	"Fastly API Key":           `(?i)fastly.{0,15}[:=]\s*['"][A-Za-z0-9_-]{32}['"]`,
	"Netlify PAT":              `(?i)netlify.{0,15}[:=]\s*['"][a-zA-Z0-9_-]{40,}['"]`,
	"Vercel Token":             `(?i)vercel.{0,15}[:=]\s*['"][a-zA-Z0-9_-]{24}['"]`,
	"Render API Key":           `rnd_[a-zA-Z0-9]{32}`,
	"Railway Token":            `(?i)railway.{0,15}[:=]\s*['"][a-zA-Z0-9_-]{36}['"]`,
	"Supabase JWT Secret":      `(?i)supabase.{0,20}secret.{0,10}[:=]\s*['"][a-zA-Z0-9_-]{40,}['"]`,
	"Supabase Service Role":    `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+`,
	"PlanetScale Token":        `pscale_tkn_[a-zA-Z0-9_\.]{43}`,
	"PlanetScale Password":     `pscale_pw_[a-zA-Z0-9_\.]{43}`,
	"Neon DB Connection":       `(?i)postgresql://[^:]+:[^@]+@[a-z0-9.-]+\.neon\.tech/[a-z0-9_]+`,
	"MongoDB Atlas URI":        `(?i)mongodb\+srv://[^:]+:[^@]+@[a-z0-9.-]+\.mongodb\.net`,
	"Elastic Cloud ID":         `(?i)cloud\.id\s*[:=]\s*['"][a-zA-Z0-9_-]+:[a-zA-Z0-9+/=]+['"]`,

	// ── Source control / CI/CD ────────────────────────────────────────────────
	"GitHub PAT (classic)":    `ghp_[0-9a-zA-Z]{36}`,
	"GitHub Fine-grained PAT": `github_pat_[0-9a-zA-Z_]{82}`,
	"GitHub Actions Secret":   `ghs_[0-9a-zA-Z]{36}`,
	"GitHub Refresh Token":    `ghr_[0-9a-zA-Z]{76}`,
	"GitLab PAT":              `glpat-[0-9a-zA-Z\-]{20}`,
	"GitLab Pipeline Trigger": `glptt-[0-9a-f]{40}`,
	"GitLab Runner Reg Token": `GR1348941[0-9a-zA-Z_-]{20}`,
	"Bitbucket App Password":  `(?i)bitbucket.{0,20}[:=]\s*['"][A-Za-z0-9]{20}['"]`,
	"CircleCI Token":          `(?i)circle.{0,15}token.{0,10}[:=]\s*['"][a-fA-F0-9]{40}['"]`,
	"Travis CI Token":         `(?i)travis.{0,15}token.{0,10}[:=]\s*['"][a-zA-Z0-9_-]{22}['"]`,
	"Jenkins API Token":       `(?i)jenkins.{0,15}token.{0,10}[:=]\s*['"][a-f0-9]{32,}['"]`,
	"Drone CI Token":          `(?i)drone.{0,15}token.{0,10}[:=]\s*['"][a-zA-Z0-9_-]{32,}['"]`,
	"Artifactory Token":       `(?i)X-JFrog-Art-Api\s*[:=]\s*['"][A-Za-z0-9_-]{40,}['"]`,
	"NPM Auth Token":          `(?i)_authToken\s*=\s*[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`,
	"Docker Hub Token":        `(?i)dockerhub.{0,15}[:=]\s*['"][a-zA-Z0-9_-]{32,}['"]`,
	"Terraform Cloud Token":   `(?i)TFC_TOKEN\s*[:=]\s*['"][a-zA-Z0-9_\-.]{14,}['"]`,
	"Vault Token":             `(?i)hvs\.[a-zA-Z0-9_-]{96}`,
	"Consul Token":            `(?i)consul.{0,15}token.{0,10}[:=]\s*['"][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}['"]`,

	// ── Comms / messaging ─────────────────────────────────────────────────────
	"Slack Webhook URL":        `https://hooks\.slack\.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8,12}/[a-zA-Z0-9_]{24}`,
	"Slack Bot Token":          `xoxb-[0-9]{11}-[0-9]{11}-[0-9a-zA-Z]{24}`,
	"Slack User Token":         `xoxp-[0-9]{11}-[0-9]{11}-[0-9]{11}-[0-9a-f]{32}`,
	"Slack App-level Token":    `xapp-[0-9]-[A-Z0-9]{11}-[0-9]{13}-[a-f0-9]{64}`,
	"Discord Bot Token":        `(?i)(discord|bot).{0,15}token.{0,10}[:=]\s*['"][MN][a-zA-Z0-9_-]{23}\.[a-zA-Z0-9_-]{6}\.[a-zA-Z0-9_-]{27}['"]`,
	"Discord Webhook URL":      `https://discord(?:app)?\.com/api/webhooks/[0-9]{18}/[a-zA-Z0-9_-]{68}`,
	"Telegram Bot Token":       `[0-9]{9}:[a-zA-Z0-9_-]{35}`,
	"Twilio Account SID":       `AC[a-z0-9]{32}`,
	"Twilio Auth Token":        `(?i)twilio.{0,20}auth.{0,10}[:=]\s*['"][a-z0-9]{32}['"]`,
	"Twilio Messaging Service": `MG[a-z0-9]{32}`,
	"SendGrid Inbound Parse":   `(?i)sendgrid.{0,15}parse.{0,10}[:=]\s*['"][A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}['"]`,
	"Mailgun API Key":          `key-[0-9a-zA-Z]{32}`,
	"Mailgun Domain Key":       `(?i)mailgun.{0,20}[:=]\s*['"][a-zA-Z0-9_-]{72}['"]`,
	"Mailchimp API Key":        `[0-9a-f]{32}-us[0-9]{1,2}`,
	"Postmark Server Token":    `(?i)postmark.{0,15}[:=]\s*['"][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}['"]`,
	"SparkPost API Key":        `(?i)sparkpost.{0,15}[:=]\s*['"][a-fA-F0-9]{40}['"]`,
	"Vonage / Nexmo API Key":   `(?i)(vonage|nexmo).{0,15}[:=]\s*['"][a-z0-9]{8}['"]`,
	"MessageBird Access Key":   `(?i)messagebird.{0,15}[:=]\s*['"][A-Za-z0-9]{25}['"]`,
	"Infobip API Key":          `(?i)infobip.{0,15}[:=]\s*['"][A-Za-z0-9]{40,}['"]`,
	"Bandwidth Token":          `(?i)bandwidth.{0,15}token.{0,10}[:=]\s*['"][A-Za-z0-9_-]{32,}['"]`,
	"Plivo Auth Token":         `(?i)plivo.{0,15}auth.{0,10}[:=]\s*['"][A-Za-z0-9]{40}['"]`,

	// ── Payment / fintech ─────────────────────────────────────────────────────
	"Stripe Test Secret":       `sk_test_[0-9a-zA-Z]{24}`,
	"Stripe Test Publishable":  `pk_test_[0-9a-zA-Z]{24}`,
	"Stripe Live Publishable":  `pk_live_[0-9a-zA-Z]{24}`,
	"Stripe Webhook Secret":    `whsec_[a-zA-Z0-9]{32,}`,
	"Stripe Idempotency Key":   `(?i)idempotency.{0,10}key.{0,10}[:=]\s*['"][a-zA-Z0-9_-]{20,}['"]`,
	"PayPal Client ID":         `(?i)paypal.{0,20}client.{0,10}[:=]\s*['"][A-Za-z0-9_-]{80}['"]`,
	"PayPal Secret":            `(?i)paypal.{0,20}secret.{0,10}[:=]\s*['"][A-Za-z0-9_-]{80}['"]`,
	"Braintree Merchant ID":    `(?i)braintree.{0,20}merchant.{0,10}[:=]\s*['"][a-z0-9]{16}['"]`,
	"Braintree Public Key":     `(?i)braintree.{0,20}public.{0,10}[:=]\s*['"][a-z0-9]{16}['"]`,
	"Braintree Private Key":    `(?i)braintree.{0,20}private.{0,10}[:=]\s*['"][a-z0-9]{32}['"]`,
	"Adyen API Key":            `AQE[a-zA-Z0-9+/]{248}[a-zA-Z0-9+/]{4}={0,2}`,
	"Adyen HMAC Key":           `(?i)adyen.{0,20}hmac.{0,10}[:=]\s*['"][A-Fa-f0-9]{64}['"]`,
	"Square Access Token":      `sq0atp-[0-9A-Za-z\-_]{22}`,
	"Square OAuth Secret":      `sq0csp-[0-9A-Za-z\-_]{43}`,
	"Klarna API Key":           `(?i)klarna.{0,15}[:=]\s*['"][a-zA-Z0-9_-]{40,}['"]`,
	"Razorpay Key ID":          `rzp_live_[A-Za-z0-9]{14}`,
	"Razorpay Key Secret":      `(?i)razorpay.{0,20}secret.{0,10}[:=]\s*['"][A-Za-z0-9]{20}['"]`,
	"Checkout.com Secret Key":  `sk_[a-z]+_[a-zA-Z0-9_-]{40}`,
	"Worldpay Service Key":     `(?i)worldpay.{0,20}[:=]\s*['"][A-Za-z0-9_-]{40,}['"]`,
	"Cybersource Merchant ID":  `(?i)cybersource.{0,20}merchant.{0,10}[:=]\s*['"][a-z0-9_-]{16,}['"]`,
	"Authorize.net API Login":  `(?i)authorizenet.{0,20}login.{0,10}[:=]\s*['"][0-9a-zA-Z]{10}['"]`,
	"2Checkout Account Number": `(?i)2checkout.{0,20}account.{0,10}[:=]\s*['"][0-9]{8}['"]`,
	"Paytm Merchant Key":       `(?i)paytm.{0,20}(merchant|mkey).{0,10}[:=]\s*['"][A-Za-z0-9@#$]{32}['"]`,
	"Coinbase API Key":         `(?i)coinbase.{0,20}key.{0,10}[:=]\s*['"][a-zA-Z0-9_-]{64}['"]`,
	"Coinbase API Secret":      `(?i)coinbase.{0,20}secret.{0,10}[:=]\s*['"][a-zA-Z0-9_-]{64}['"]`,
	"Binance API Key":          `(?i)binance.{0,20}(api.?key|key).{0,10}[:=]\s*['"][A-Za-z0-9]{64}['"]`,
	"Kraken API Key":           `(?i)kraken.{0,20}key.{0,10}[:=]\s*['"][A-Za-z0-9/+=]{56}['"]`,
	"BitPay API Token":         `(?i)bitpay.{0,15}[:=]\s*['"][a-zA-Z0-9_-]{40}['"]`,
	"Plaid Client ID":          `(?i)plaid.{0,20}client.{0,10}[:=]\s*['"][a-z0-9]{24}['"]`,
	"Plaid Secret":             `(?i)plaid.{0,20}secret.{0,10}[:=]\s*['"][a-z0-9]{30}['"]`,
	"Open Banking TPP Secret":  `(?i)tpp.{0,15}(secret|key).{0,10}[:=]\s*['"][A-Za-z0-9_-]{32,}['"]`,
	"PCI DSS Merchant Cert":    `(?i)merchant.{0,15}cert.{0,10}[:=]\s*'[A-Za-z0-9+/=]{44,}'`,

	// ── Social / OAuth ────────────────────────────────────────────────────────
	"Facebook App Secret":         `(?i)(facebook|fb).{0,20}(secret|app.?secret).{0,10}[:=]\s*['"][0-9a-f]{32}['"]`,
	"Facebook Access Token":       `EAA[a-zA-Z0-9]{50,}`,
	"Instagram Access Token":      `(?i)instagram.{0,20}token.{0,10}[:=]\s*['"][0-9]{10,}\.[a-f0-9]{32,}['"]`,
	"Twitter Bearer Token":        `AAAA[a-zA-Z0-9%]{95,}`,
	"Twitter Consumer Secret":     `(?i)twitter.{0,20}(consumer|api).{0,10}secret.{0,10}[:=]\s*['"][a-zA-Z0-9]{50}['"]`,
	"Twitter Access Token Secret": `(?i)twitter.{0,20}access.{0,10}secret.{0,10}[:=]\s*['"][a-zA-Z0-9]{45}['"]`,
	"LinkedIn Client Secret":      `(?i)linkedin.{0,20}(secret|client.?secret).{0,10}[:=]\s*['"][a-zA-Z0-9]{16}['"]`,
	"Google OAuth Client Secret":  `GOCSPX-[a-zA-Z0-9_-]{28}`,
	"Apple ID Key":                `(?i)apple.{0,20}(key|auth).{0,10}[:=]\s*['"]-----BEGIN PRIVATE KEY-----`,
	"Apple Team ID":               `(?i)apple.{0,15}team.{0,10}[:=]\s*['"][A-Z0-9]{10}['"]`,
	"Apple Bundle ID":             `(?i)bundle.?id\s*[:=]\s*['"][a-z]{2,}\.[a-z][a-z.]{4,}['"]`,
	"Microsoft App Secret":        `(?i)(microsoft|ms).{0,20}(secret|app.?secret).{0,10}[:=]\s*['"][a-zA-Z0-9.~_-]{34}['"]`,
	"Spotify Client Secret":       `(?i)spotify.{0,20}(secret|client.?secret).{0,10}[:=]\s*['"][a-f0-9]{32}['"]`,
	"GitHub App Private Key":      `(?i)-----BEGIN RSA PRIVATE KEY-----\r?\nMI`,
	"Okta API Token":              `00[a-zA-Z0-9_-]{40}`,
	"Auth0 Client Secret":         `(?i)auth0.{0,20}(secret|client.?secret).{0,10}[:=]\s*['"][a-zA-Z0-9_-]{32,}['"]`,
	"Keycloak Client Secret":      `(?i)keycloak.{0,20}(secret|client.?secret).{0,10}[:=]\s*['"][a-zA-Z0-9_-]{32,}['"]`,

	// ── Database connection strings ────────────────────────────────────────────
	"PostgreSQL Connection String": `(?i)postgres(?:ql)?://[^:]+:[^@]+@[^/]+/[a-z0-9_]+`,
	"MySQL Connection String":      `(?i)mysql://[^:]+:[^@]+@[^/]+/[a-z0-9_]+`,
	"MySQL Legacy DSN":             `(?i)mysql:host=[^;]+;dbname=[^;]+;user=[^;]+;password=[^'"]+`,
	"MSSQL Connection String":      `(?i)Data Source=[^;]+;Initial Catalog=[^;]+;User ID=[^;]+;Password=[^;]+`,
	"Redis Connection String":      `(?i)redis://(:(.+)@)?[a-z0-9._-]+(:[0-9]{4,5})?(/[0-9]+)?`,
	"Redis AUTH password":          `(?i)redis.{0,20}(auth|password|pass).{0,10}[:=]\s*['"][^'"]{8,}['"]`,
	"Cassandra Credentials":        `(?i)cassandra.{0,20}(password|pass|secret).{0,10}[:=]\s*['"][^'"]{8,}['"]`,
	"Elasticsearch HTTP Auth":      `(?i)http[s]?://[^:]+:[^@]+@[a-z0-9._-]+:[0-9]{4}`,
	"RabbitMQ Connection":          `(?i)amqp[s]?://[^:]+:[^@]+@[a-z0-9._-]+(:[0-9]{4,5})?/[a-z0-9]+`,
	"Kafka SASL Password":          `(?i)sasl.{0,20}password.{0,10}[:=]\s*['"][^'"]{8,}['"]`,
	"InfluxDB Token":               `(?i)influxdb.{0,20}token.{0,10}[:=]\s*['"][a-zA-Z0-9_-]{86}==?['"]`,
	"CockroachDB URI":              `(?i)cockroachdb://[^:]+:[^@]+@[a-z0-9._-]+:[0-9]{5}/[a-z0-9_]+`,
	"Snowflake Account":            `(?i)snowflake.{0,20}(password|private.?key).{0,10}[:=]\s*['"][^'"]{8,}['"]`,
	"BigQuery Service Account":     `(?i)"project_id":\s*"[a-z0-9_-]+".*"private_key":\s*"-----BEGIN`,
	"Databricks PAT":               `dapi[a-f0-9]{32}`,
	"Pinecone API Key":             `(?i)pinecone.{0,15}[:=]\s*['"][a-zA-Z0-9_-]{36,}['"]`,

	// ── Crypto / Web3 ─────────────────────────────────────────────────────────
	"Ethereum Private Key":     `(?i)(eth|ethereum).{0,20}(private.?key|pk|secret).{0,10}[:=]\s*['"]0x[0-9a-fA-F]{64}['"]`,
	"Ethereum Raw Private Key": `\b0x[0-9a-fA-F]{64}\b`,
	"Bitcoin WIF Private Key":  `[5KL][1-9A-HJ-NP-Za-km-z]{51}`,
	"Bitcoin WIF Compressed":   `[cKL][1-9A-HJ-NP-Za-km-z]{51}`,
	"Solana Private Key":       `(?i)solana.{0,20}(private.?key|secret).{0,10}[:=]\s*['"][1-9A-HJ-NP-Za-km-z]{87,88}['"]`,
	"Mnemonic Seed Phrase":     `\b(word|seed|mnemonic|phrase|recovery)\s*[:=]\s*['"][a-z]+( [a-z]+){11,23}['"]`,
	"Infura Project Secret":    `(?i)infura.{0,20}(secret|project.?secret).{0,10}[:=]\s*['"][a-f0-9]{32}['"]`,
	"Alchemy API Key":          `(?i)alchemy.{0,15}[:=]\s*['"][a-zA-Z0-9_-]{32,}['"]`,
	"Moralis API Key":          `(?i)moralis.{0,15}[:=]\s*['"][a-zA-Z0-9_-]{32,}['"]`,
	"Web3 RPC URL with Key":    `https://[a-z.-]+\.(infura|alchemy|quicknode|ankr)\.io/v[0-9]/[a-f0-9]{32}`,
	"Trezor Connect Secret":    `(?i)trezor.{0,15}secret.{0,10}[:=]\s*['"][A-Za-z0-9_-]{40,}['"]`,
	"MetaMask Vault Data":      `(?i)"vault"\s*:\s*"\{.*"data".*"iv".*"salt"`,

	// ── Private keys / certs ──────────────────────────────────────────────────
	"EC Private Key":              `-----BEGIN EC PRIVATE KEY-----`,
	"DSA Private Key":             `-----BEGIN DSA PRIVATE KEY-----`,
	"OpenSSH Private Key":         `-----BEGIN OPENSSH PRIVATE KEY-----`,
	"PGP Private Key Block":       `-----BEGIN PGP PRIVATE KEY BLOCK-----`,
	"PKCS8 Private Key":           `-----BEGIN PRIVATE KEY-----`,
	"Encrypted Private Key":       `-----BEGIN ENCRYPTED PRIVATE KEY-----`,
	"Certificate Signing Request": `-----BEGIN CERTIFICATE REQUEST-----`,
	"X.509 Certificate (inline)":  `-----BEGIN CERTIFICATE-----`,
	"Java KeyStore Password":      `(?i)(keystore|jks|keystore.?pass|storepass).{0,10}[:=]\s*['"][^'"]{6,}['"]`,
	"Kubernetes Secret (b64)":     `(?i)kind:\s*Secret[\s\S]{0,200}data:[\s\S]{0,200}[a-zA-Z0-9_-]+:\s*[A-Za-z0-9+/]{40,}={0,2}`,
	"Kubernetes Kubeconfig Token": `(?i)token:\s*[A-Za-z0-9_-]{86,90}\.{1}[A-Za-z0-9_-]{6,}`,
	"SSH Host Private Key":        `(?i)ssh.{0,20}(private|host).{0,10}key.{0,10}[:=]\s*['"]-----BEGIN`,

	// ── Analytics / monitoring ────────────────────────────────────────────────
	"Datadog API Key":         `(?i)datadog.{0,20}(api.?key|key).{0,10}[:=]\s*['"][a-f0-9]{32}['"]`,
	"Datadog App Key":         `(?i)datadog.{0,20}app.?key.{0,10}[:=]\s*['"][a-f0-9]{40}['"]`,
	"New Relic License Key":   `NRJS-[a-f0-9]{19}[a-f0-9]{7}`,
	"New Relic API Key":       `NRAK-[A-Z0-9]{27}`,
	"Sentry DSN":              `https://[a-f0-9]{32}@[a-z0-9]+\.ingest\.sentry\.io/[0-9]+`,
	"Bugsnag API Key":         `(?i)bugsnag.{0,15}[:=]\s*['"][a-f0-9]{32}['"]`,
	"Rollbar Token":           `(?i)rollbar.{0,15}[:=]\s*['"][a-f0-9]{32}['"]`,
	"Honeybadger API Key":     `(?i)honeybadger.{0,15}[:=]\s*['"][a-zA-Z0-9_/+]{20,}['"]`,
	"Loggly Token":            `(?i)loggly.{0,15}[:=]\s*['"][a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}['"]`,
	"Sumologic Collector URL": `https://collectors\.sumologic\.com/receiver/v1/http/[a-zA-Z0-9=]{64,}`,
	"Mixpanel Token":          `(?i)mixpanel.{0,15}[:=]\s*['"][a-f0-9]{32}['"]`,
	"Amplitude API Key":       `(?i)amplitude.{0,15}[:=]\s*['"][a-f0-9]{32}['"]`,
	"Segment Write Key":       `(?i)segment.{0,15}write.?key.{0,10}[:=]\s*['"][a-zA-Z0-9]{35}['"]`,
	"Heap App ID":             `(?i)heap.{0,15}(app.?id|id).{0,10}[:=]\s*['"][0-9]{10}['"]`,
	"FullStory Org ID":        `(?i)fullstory.{0,15}org.{0,10}[:=]\s*['"][A-Z0-9]{5,8}['"]`,
	"Hotjar Site ID":          `(?i)hotjar.{0,15}(id|site.?id).{0,10}[:=]\s*['"][0-9]{7}['"]`,
	"Google Analytics ID":     `(?i)(gtag|ga|analytics).{0,20}(id|key).{0,10}[:=]\s*['"]G-[A-Z0-9]{10}['"]`,
	"Google Tag Manager ID":   `GTM-[A-Z0-9]{7}`,
	"Pendo API Key":           `(?i)pendo.{0,15}[:=]\s*['"][a-zA-Z0-9_-]{30,}['"]`,

	// ── Map / geolocation ─────────────────────────────────────────────────────
	"Google Maps API Key": `AIza[0-9A-Za-z\-_]{35}`,
	"Mapbox Secret Token": `sk\.eyJ[a-zA-Z0-9._-]{100,}`,
	"Mapbox Public Token": `pk\.eyJ[a-zA-Z0-9._-]{100,}`,
	"HERE API Key":        `(?i)here.{0,15}(api.?key|key).{0,10}[:=]\s*['"][a-zA-Z0-9_-]{43}['"]`,
	"TomTom API Key":      `(?i)tomtom.{0,15}[:=]\s*['"][a-zA-Z0-9]{32}['"]`,
	"OpenCage API Key":    `(?i)opencage.{0,15}[:=]\s*['"][a-f0-9]{32}['"]`,

	// ── Internal network leaks ────────────────────────────────────────────────
	"Internal Hostname Leak":      `(?i)(host|hostname|server|endpoint|db.?host)\s*[:=]\s*['"][a-z0-9_-]+(\.internal|\.local|\.corp|\.intranet|\.lan)[^'"]*['"]`,
	"Docker Registry Credentials": `(?i)(docker.?registry|registry).{0,20}(pass|password|secret).{0,10}[:=]\s*['"][^'"]{8,}['"]`,
	"Kubernetes Namespace Secret": `(?i)namespace\s*[:=]\s*['"]kube-system['"]`,
	"Spring Boot Datasource PW":   `(?i)spring\.datasource\.password\s*=\s*[^\s#]{4,}`,
	"Spring Boot JWT Secret":      `(?i)jwt\.secret\s*=\s*[^\s#]{16,}`,
	"Django Secret Key":           `(?i)SECRET_KEY\s*=\s*['"][a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};':\"\\|,.<>/?]{40,}['"]`,
	"Rails Secret Key Base":       `(?i)secret_key_base\s*[:=]\s*['"][a-f0-9]{128}['"]`,
	"Laravel APP_KEY":             `base64:[A-Za-z0-9+/]{43}=`,
	"Express Session Secret":      `(?i)(session|cookie).{0,15}secret.{0,10}[:=]\s*['"][^'"]{16,}['"]`,
	"Next.js NEXTAUTH_SECRET":     `(?i)NEXTAUTH_SECRET\s*[:=]\s*['"][^'"]{16,}['"]`,
	"Nuxt Runtime Config Secret":  `(?i)(nuxt|runtime).{0,20}secret.{0,10}[:=]\s*['"][^'"]{16,}['"]`,
	"WordPress DB Password":       `(?i)define\s*\(\s*['"]DB_PASSWORD['"]\s*,\s*['"][^'"]{4,}['"]\s*\)`,
	"WordPress Auth Key":          `(?i)define\s*\(\s*['"]AUTH_KEY['"]\s*,\s*['"][^'"]{20,}['"]\s*\)`,
	"WordPress Salt Leak":         `(?i)define\s*\(\s*['"]SECURE_AUTH_SALT['"]\s*,\s*['"][^'"]{20,}['"]\s*\)`,
	"Drupal Hash Salt":            `(?i)\$settings\['hash_salt'\]\s*=\s*'[a-zA-Z0-9/+=]{74}'`,
	"Symfony App Secret":          `(?i)APP_SECRET\s*=\s*[a-f0-9]{32}`,

	// ── AZ ecosystem extended ─────────────────────────────────────────────────
	"AZ Xalq Bank":           `(?i)(xalqbank|xalq).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Rabitabank":          `(?i)(rabitabank|rabita).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Unibank":             `(?i)(unibank|uni_bank).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Turanbank":           `(?i)(turanbank|turan_bank).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ AccessBank":          `(?i)(accessbank|access_bank).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Expressbank":         `(?i)(expressbank|express_bank).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Yelobank":            `(?i)(yelobank|yelo_bank|yelo).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ VTB Azerbaijan":      `(?i)(vtb_az|vtbaz|vtb).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Ziraat Bank AZ":      `(?i)(ziraatbank|ziraat_az|ziraat).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ AtaBank":             `(?i)(atabank|ata_bank).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ AFB Bank":            `(?i)(afbbank|afb_bank|afb).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Amrahbank":           `(?i)(amrahbank|amrah_bank|amrah).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ PremiumBank":         `(?i)(premiumbank|premium_bank).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Demir Bank":          `(?i)(demirbank|demir_bank|demir).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Kredobank":           `(?i)(kredobank|kredo_bank).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Bank Standard":       `(?i)(bank_standard|bankstandard|bstandard).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ M10 Wallet":          `(?i)(m10|m10pay|m10_wallet).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ PashaPay":            `(?i)(pashapay|pasha_pay).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ PulPay":              `(?i)(pulpay|pul_pay).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ E-Manat":             `(?i)(e_manat|emanat|e-manat).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ PayRiff":             `(?i)(payriff|pay_riff).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Fido":                `(?i)(fido|fidoaz|fido_az).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ PortManat":           `(?i)(portmanat|port_manat).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ GoldenPay":           `(?i)(goldenpay|golden_pay).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Epul":                `(?i)(epul|e_pul).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Mpay":                `(?i)(mpay|m_pay|mpayz).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Payonix":             `(?i)(payonix|pay_onix).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Kontakt Home":        `(?i)(kontakt|kontakt_home|kontakthome).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Trendyol AZ":         `(?i)(trendyol_az|trendyol).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Azercell API":        `(?i)(azercell).{0,20}(api|key|token|secret).{0,10}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Bakcell API":         `(?i)(bakcell).{0,20}(api|key|token|secret).{0,10}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Nar Mobile API":      `(?i)(nar_mobile|narmobile|nar).{0,20}(api|key|token|secret).{0,10}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ SOCAR API":           `(?i)(socar).{0,20}(api|key|token|secret).{0,10}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ e-Gov Token":         `(?i)(e_gov|egov|mygov|e_sosial|asan_imza).{0,20}(token|key|secret|api).{0,10}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Taxes (Vergiler)":    `(?i)(vergiler|taxes_az|edv).{0,20}(token|key|secret|api).{0,10}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Azerbaijan Airlines": `(?i)(azal|azerbaijanairlines).{0,20}(token|key|secret|api).{0,10}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ AZAL Miles":          `(?i)(azal_miles|azalmiles).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Wolt Courier Token":  `(?i)(wolt).{0,20}(token|key|secret|api).{0,10}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Bolt Token":          `(?i)(bolt_az|bolttaxi).{0,20}(token|key|secret).{0,10}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ iTicket":             `(?i)(iticket|iticket_az).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ BakiKart":            `(?i)(bakikart|baki_kart).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Metro Token":         `(?i)(metro_az|bakimetro).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ Customs (Gomruk)":    `(?i)(gomruk|customs_az).{0,20}(token|key|secret).{0,10}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ CBS/Core Banking":    `(?i)(finacle|flexcube|t24|temenos|fincore).{0,20}(url|host|pass|secret|key).{0,10}[:=]\s*['"]([A-Za-z0-9@:./_-]{10,})['"]`,
	"AZ SWIFT Gateway":       `(?i)(swift_gateway|swiftgw|swift.?gw).{0,20}(pass|secret|key|token).{0,10}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ OTP Service":         `(?i)(otp_service|sms_otp|otp_secret).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{10,})['"]`,
	"AZ National ID":         `(?i)(fin_kod|finkod|national_id|passport_no|voen).{0,15}[:=]\s*['"]([A-Za-z0-9_-]{5,30})['"]`,
	"AZ FIN Code":            `\b[A-Z0-9]{7}\b`,
	"AZ VOEN (Tax ID)":       `\b[0-9]{10}\b`,
	"AZ Phone Number":        `(?i)(phone|tel|mobile).{0,10}[:=]\s*['"](\+994|0)[0-9]{9}['"]`,
}

var PatternEntropy = map[string]float64{
	// Original
	"Google API Key":     3.0,
	"AWS Access Key":     3.0,
	"Slack Token":        3.0,
	"Extended JWT Token": 4.0,
	"AWS Secret Key":     3.5,

	// Cloud
	"AWS Session Token":        4.0,
	"GCP Service Account JSON": 3.5,
	"Azure Storage Key":        4.5,
	"Azure SAS Token":          3.5,
	"DigitalOcean PAT":         4.0,
	"Vault Token":              4.5,
	"Kubernetes Secret (b64)":  4.0,
	"Databricks PAT":           4.0,

	// Source control / CI
	"GitHub PAT (classic)":    3.5,
	"GitHub Fine-grained PAT": 4.0,
	"GitLab PAT":              3.5,

	// Comms
	"Slack Webhook URL":  3.5,
	"Telegram Bot Token": 3.5,
	"Mailchimp API Key":  3.0,

	// Payment
	"Stripe Test Secret":  3.5,
	"Adyen API Key":       4.5,
	"Square Access Token": 3.5,
	"Razorpay Key ID":     3.0,
	"Coinbase API Key":    4.0,
	"Binance API Key":     4.0,

	// Social / OAuth
	"Facebook Access Token":      3.5,
	"Twitter Bearer Token":       4.0,
	"Google OAuth Client Secret": 3.5,

	// DB
	"PostgreSQL Connection String": 3.5,
	"Redis Connection String":      3.0,
	"InfluxDB Token":               4.5,
	"Snowflake Account":            3.5,
	"Databricks PAT":               4.0,

	// Crypto
	"Ethereum Raw Private Key": 4.0,
	"Bitcoin WIF Private Key":  4.0,
	"Infura Project Secret":    3.5,

	// Certs / Keys
	"EC Private Key":        4.0,
	"OpenSSH Private Key":   4.0,
	"PGP Private Key Block": 4.0,

	// Frameworks
	"Django Secret Key":     4.0,
	"Rails Secret Key Base": 4.5,
	"Laravel APP_KEY":       4.0,

	// AZ
	"AZ Kapital Bank":     3.0,
	"AZ CBS/Core Banking": 3.5,
	"AZ SWIFT Gateway":    4.0,
	"AZ e-Gov Token":      3.0,
	"AZ Ethereum Raw":     4.0,
}

var DefaultEntropy = 0.0

var BankingKeywordList = []string{
	// ── Original list ──────────────────────────────────────────────────────────
	"username", "password", "passwd", "pwd", "auth", "authentication", "api_key",
	"apikey", "secret", "token", "access_token", "refresh_token", "jwt",
	"iban", "swift", "swift_code", "bic", "bic_code", "sort_code", "routing_number",
	"account_number", "account_no", "acct_no", "biller_code", "payee", "pan",
	"cvv", "cvc", "card_number", "credit_card", "debit_card", "expiry_date",
	"pin", "pin_code", "atm_pin", "balance", "balance_amt", "transaction_id",
	"txn_id", "payment_token", "cardholder_name", "kyc", "kyc_token", "aml",
	"core_banking", "cbs_url", "teller_id", "branch_id", "teller_password",
	"swift_gateway", "fincore", "finacle", "flexcube", "t24", "temenos",
	"otp", "otp_secret", "mfa", "mfa_secret", "2fa", "2fa_seed", "totp",
	"sms_token", "verification_code", "db_user", "db_pass", "db_password",
	"database_url", "redis_url", "mongo_url", "sql_conn", "jdbc_url", "aws_secret",
	"aws_key", "azure_key", "gcp_key", "s3_bucket", "azure_blob", "admin",
	"admin_pass", "admin_user", "root_pass", "superuser", "ssn", "social_security",
	"national_id", "passport_no", "driver_license", "client_id", "client_secret",
	"oauth_token", "bearer_token", "private_key", "public_key", "ssl_cert",
	"cert_password", "keystore_pass", "truststore_pass", "account", "customer_id",
	"cid", "card_expiry", "card_token", "vault_key", "enc_key", "aes_key",
	"des_key", "rsa_key", "mac_key", "pgp_key", "ssh_key", "api_token", "api_secret",
	"app_secret", "app_key", "session_id", "session_token", "cookie_secret",
	"csrf_token", "xsrf_token", "webhook_secret", "slack_token", "twilio_token",
	"sendgrid_key", "mailgun_key", "stripe_key", "paypal_secret", "braintree_key",
	"adyen_key", "square_key", "plaid_secret", "plaid_client", "yodlee_secret",
	"finicity_key", "mastercard_key", "visa_api", "amex_key", "discover_api",
	"western_union", "moneygram", "crypto_key", "wallet_key", "blockchain_api",
	"eth_key", "btc_key", "contract_address", "infura_key", "alchemy_key",
	"moralis_key", "binance_api", "coinbase_api", "kraken_api", "ftx_api",
	"kucoin_api", "huobi_api", "okx_api", "bitfinex_api", "bitstamp_api",
	"gemini_api", "bybit_api", "deribit_api", "paxos_api", "circle_api",
	"tether_api", "usdc_api", "dai_api", "maker_api", "compound_api",
	"aave_api", "uniswap_api", "sushiswap_api", "pancakeswap_api", "1inch_api",
	"curve_api", "balancer_api", "yearn_api", "synthetix_api", "chainlink_api",
	"band_api", "graph_api", "api_url", "api_endpoint", "graphql_url",
	"rest_url", "soap_url", "grpc_url", "rpc_url", "ws_url", "wss_url",
	"socket_url", "mqtt_url", "amqp_url", "kafka_url", "rabbitmq_url",
	"redis_host", "memcached_host", "elastic_host", "kibana_host", "logstash_host",
	"splunk_host", "datadog_key", "newrelic_key", "dynatrace_key", "appdynamics_key",
	"sentry_dsn", "bugsnag_key", "rollbar_token", "raygun_key", "loggly_token",
	"papertrail_port", "sumologic_url", "mixpanel_token", "segment_key",
	"amplitude_key", "heap_id", "hotjar_id", "fullstory_org", "google_maps_key",
	"bing_maps_key", "mapbox_token", "here_app_id", "tomtom_key", "foursquare_id",
	"bank_api", "bank_secret", "bank_token", "bank_key", "bank_pass",
	"merchant_id", "merchant_key", "merchant_secret", "terminal_id", "pos_id",
	"acquirer_id", "issuer_id", "bin_number", "card_brand", "card_type",
	"funding_source", "payment_method", "payment_gateway", "payment_processor",
	"clearing_house", "settlement_bank", "correspondent_bank", "intermediary_bank",
	"beneficiary_bank", "originating_bank", "receiving_bank", "sending_bank",
	"wire_transfer", "ach_transfer", "sepa_transfer", "rtgs_transfer", "chaps_transfer",
	"bacs_transfer", "fps_transfer", "zelle_transfer", "venmo_transfer", "cashapp_transfer",
	"paypal_transfer", "applepay_transfer", "googlepay_transfer", "samsungpay_transfer",
	"e_manat", "emanat", "mpay", "modenis", "payonix",
	"payriff", "kassam", "fido", "portmanat", "kassam_az",
	"smartpay", "az_smartpay", "komek", "xalqbank", "xalq",
	"turanbank", "turan", "rabitabank", "rabita", "yelo",
	"yelobank", "unibank", "vtb", "vtb_az", "mbt",
	"accessbank", "expressbank", "express", "premiumbank", "afb",
	"afbbank", "ziraat", "ziraatbank", "melli", "melli_iran",
	"azerturk", "azerturkbank", "asb", "amrah", "amrahbank",
	"demir", "demirbank", "parabank", "kredobank", "deka",
	"dekabank", "atra", "atrabank", "kavkaz", "kavkaz_inkisaf",
	"borcali", "royal", "royalbank", "texnika", "texnikabank",
	"bank_standard", "standard", "azal", "buta", "buta_airways",
	"wolt", "bolt", "uber_az", "yango", "maxim",
	"trendyol", "alinino", "kontakt", "kontakt_home", "baku_electronics",
	"irshad", "irshad_electronics", "music_gallery", "maxi", "optimal",
	"optimal_electronics", "koton", "zara", "bershka", "pull_and_bear",
	"mango", "lc_waikiki", "defacto", "azercosmos", "azerenerji",
	"azersu", "azeriqaz", "azerisiq", "socar", "bp_az",
	"e_gov", "e_gov_az", "mygov", "mygov_az", "e_sosial",
	"e_sosial_az", "e_sehiyye", "e_customs", "asan", "asan_imza",
	"digital_login", "simac", "sima", "daxili_ishler", "mia",
	"mia_az", "dyyp", "dyp", "gomruk", "customs_az",
	"vergiler", "taxes_az", "edv", "edv_geri_al", "kobia",
	"e_kobia", "azpost", "azerpoct", "dhl_az", "fedex_az",
	"ups_az", "aramex_az", "camex", "starex", "dynamex",
	"limak", "kango", "mova", "vipex", "flyex",
	"colibri", "m10", "pashapay", "pulpay", "kassir",
	"iticket", "iticket_az", "ticket_az", "cinemastercard", "park_cinema",
	"cinema_plus", "ayna", "ayna_az", "bna", "bakikart",
	"metro_az", "azerbaijan_airlines", "azal_miles", "salam_baku", "airport_az",
	"aztv", "itv", "cbc", "cbc_sport", "arb",
	"space_tv", "xazar_tv", "atv_az",

	// ══════════════════════════════════════════════════════════════════════════
	// NEW KEYWORDS (+500)
	// ══════════════════════════════════════════════════════════════════════════

	// ── Generic credential variants ────────────────────────────────────────────
	"pass", "passphrase", "secret_key", "secret_token", "private_token",
	"auth_token", "auth_key", "auth_secret", "authorization", "credential",
	"credentials", "user_secret", "user_token", "user_key", "user_pass",
	"user_password", "login_token", "login_key", "login_secret",
	"service_account", "service_key", "service_secret", "service_token",
	"system_key", "system_secret", "system_token", "master_key", "master_secret",
	"master_password", "root_key", "root_token", "root_secret",
	"admin_key", "admin_token", "admin_secret",
	"super_admin", "super_key", "super_secret",
	"operator_key", "operator_token", "operator_secret",
	"manager_key", "manager_token", "manager_secret",
	"internal_key", "internal_token", "internal_secret",
	"external_key", "external_token", "external_secret",
	"integration_key", "integration_token", "integration_secret",
	"partner_key", "partner_token", "partner_secret",
	"vendor_key", "vendor_token", "vendor_secret",
	"client_key", "client_token", "client_pass",
	"app_id", "app_token", "application_key", "application_secret",
	"consumer_key", "consumer_secret", "consumer_token",
	"provider_key", "provider_secret", "provider_token",

	// ── Cloud / infra ──────────────────────────────────────────────────────────
	"aws_access_key_id", "aws_secret_access_key", "aws_session_token",
	"aws_region", "aws_account_id", "aws_role_arn", "aws_lambda_arn",
	"gcp_project_id", "gcp_service_account", "gcp_private_key_id",
	"google_credentials", "google_application_credentials",
	"azure_subscription_id", "azure_client_id", "azure_client_secret",
	"azure_tenant_id", "azure_storage_account", "azure_storage_key",
	"azure_connection_string", "azure_sas_token", "azure_access_token",
	"do_access_token", "do_spaces_key", "do_spaces_secret",
	"heroku_api_key", "cloudflare_api_key", "cloudflare_zone_id",
	"cloudflare_account_id", "fastly_api_key", "netlify_access_token",
	"vercel_token", "render_api_key", "railway_token",
	"supabase_key", "supabase_url", "supabase_secret",
	"planetscale_password", "planetscale_token",
	"neon_connection_string", "turso_auth_token",
	"upstash_redis_url", "upstash_redis_token",
	"elastic_cloud_id", "elastic_api_key",
	"databricks_token", "databricks_host",
	"snowflake_password", "snowflake_account", "snowflake_warehouse",
	"bigquery_credentials", "bigquery_dataset",
	"vault_token", "vault_addr", "vault_namespace",
	"consul_token", "consul_http_token",
	"nomad_token", "nomad_addr",
	"terraform_token", "tf_api_token",
	"pulumi_access_token",
	"k8s_token", "kube_token", "kubectl_token",
	"kubeconfig", "kube_config",
	"docker_password", "docker_token", "registry_password",
	"artifactory_token", "nexus_password",
	"jfrog_token", "jfrog_password",
	"npm_token", "npm_auth_token", "yarn_token",
	"pypi_token", "gemstone_token", "cargo_token",

	// ── Database ──────────────────────────────────────────────────────────────
	"db_host", "db_port", "db_name", "db_user", "db_pass",
	"db_password", "db_secret", "db_token", "db_url", "db_uri",
	"database_host", "database_port", "database_name",
	"database_user", "database_password", "database_uri",
	"mysql_user", "mysql_password", "mysql_host", "mysql_port",
	"postgres_user", "postgres_password", "postgres_host", "postgres_port",
	"postgresql_url", "pg_password", "pg_user", "pg_host",
	"mssql_user", "mssql_password", "mssql_host",
	"oracle_user", "oracle_password", "oracle_host", "oracle_sid",
	"mongo_user", "mongo_password", "mongo_host", "mongodb_uri",
	"redis_password", "redis_auth", "redis_token",
	"cassandra_user", "cassandra_password",
	"elastic_user", "elastic_password",
	"kafka_password", "kafka_sasl_password",
	"rabbitmq_password", "amqp_password",
	"influxdb_token", "influxdb_password",
	"clickhouse_password", "clickhouse_user",
	"cockroachdb_url", "tidb_password",
	"dynamodb_table", "dynamodb_region",
	"firestore_credentials", "bigtable_credentials",
	"pinecone_api_key", "weaviate_api_key", "qdrant_api_key",
	"connection_string", "conn_string", "dsn",
	"jdbc_connection", "odbc_connection",

	// ── Auth / identity ────────────────────────────────────────────────────────
	"id_token", "access_token_secret", "refresh_token_secret",
	"oauth_client_id", "oauth_client_secret", "oauth_access_token",
	"oauth_refresh_token", "oauth_token_secret",
	"oidc_client_secret", "oidc_issuer", "oidc_audience",
	"saml_cert", "saml_key", "saml_secret",
	"ldap_bind_dn", "ldap_bind_password", "ldap_user", "ldap_pass",
	"active_directory_password", "ad_password", "ad_secret",
	"okta_api_token", "okta_client_secret", "okta_issuer",
	"auth0_client_secret", "auth0_domain", "auth0_management_token",
	"keycloak_secret", "keycloak_client_secret",
	"firebase_api_key", "firebase_app_id", "firebase_secret",
	"cognito_client_secret", "cognito_pool_id", "cognito_region",
	"jwt_secret", "jwt_key", "jwt_private_key",
	"jwt_public_key", "jwt_issuer", "jwt_audience",
	"signing_key", "signing_secret", "hmac_key", "hmac_secret",
	"encryption_key", "decryption_key", "symmetric_key",
	"asymmetric_key", "public_cert", "private_cert",
	"x509_cert", "ssl_key", "tls_key", "tls_cert",
	"ca_cert", "ca_key", "root_ca", "intermediate_ca",
	"p12_password", "pfx_password", "jks_password", "pkcs12_password",

	// ── Session / cookie ──────────────────────────────────────────────────────
	"session_secret", "session_key", "session_password",
	"cookie_key", "cookie_token", "cookie_password",
	"cookie_domain", "cookie_name",
	"csrf_secret", "xsrf_secret", "anti_csrf_token",
	"nextauth_secret", "next_auth_secret",
	"nuxt_secret", "nuxt_session_key",
	"express_session_secret", "flask_secret_key",
	"django_secret_key", "rails_secret_key_base",
	"laravel_app_key", "symfony_app_secret",
	"wordpress_auth_key", "wordpress_secure_auth_key",
	"wordpress_logged_in_key", "wordpress_nonce_key",
	"drupal_hash_salt", "joomla_secret",

	// ── Payment / banking extended ────────────────────────────────────────────
	"stripe_secret_key", "stripe_publishable_key",
	"stripe_webhook_secret", "stripe_connect_secret",
	"paypal_client_id", "paypal_client_secret",
	"paypal_webhook_id", "paypal_mode",
	"braintree_merchant_id", "braintree_public_key", "braintree_private_key",
	"adyen_api_key", "adyen_hmac_key", "adyen_client_key",
	"klarna_api_key", "klarna_username", "klarna_password",
	"square_access_token", "square_app_id", "square_location_id",
	"razorpay_key_id", "razorpay_key_secret",
	"checkout_secret_key", "checkout_public_key",
	"worldpay_service_key", "worldpay_client_key",
	"cybersource_merchant_id", "cybersource_transaction_key",
	"authorize_net_login", "authorize_net_transaction_key",
	"paytm_merchant_id", "paytm_merchant_key",
	"mollie_api_key", "mollie_webhook_secret",
	"iyzipay_api_key", "iyzipay_secret_key",
	"paddle_api_key", "paddle_vendor_id",
	"gocardless_access_token", "gocardless_webhook_secret",
	"transferwise_api_token", "wise_api_token",
	"revolut_api_key", "n26_api_token",
	"monzo_access_token", "starling_api_token",
	"open_banking_client_id", "open_banking_client_secret",
	"psd2_client_id", "psd2_client_secret",
	"iso20022_signing_key", "sepa_mandate_id",
	"ach_account_number", "ach_routing_number",
	"wire_routing_number", "wire_account_number",
	"sort_code_account", "bsb_number",
	"clabe_number", "ifsc_code",
	"transit_number", "institution_number",
	"micr_line", "check_number",
	"payment_profile_id", "customer_vault_id",
	"subscription_id", "plan_id",
	"invoice_id", "receipt_id",
	"refund_id", "dispute_id",
	"chargeback_id", "reversal_id",
	"authorization_code", "capture_id",
	"settlement_id", "batch_id",
	"terminal_serial", "device_id",
	"emv_tag", "icc_data",
	"track1_data", "track2_data",
	"dukpt_key", "tdea_key",
	"hsm_key", "kek_key", "dek_key",
	"zpk_key", "pvk_key", "cvk_key",
	"lmk_key",

	// ── Comms extended ────────────────────────────────────────────────────────
	"slack_webhook", "slack_bot_token", "slack_app_token",
	"discord_token", "discord_webhook", "discord_client_secret",
	"telegram_token", "telegram_bot_token", "telegram_api_hash",
	"telegram_api_id",
	"twilio_account_sid", "twilio_auth_token", "twilio_api_key",
	"sendgrid_api_key", "sendgrid_webhook_key",
	"mailgun_api_key", "mailgun_domain", "mailgun_webhook_key",
	"mailchimp_api_key", "mailchimp_list_id",
	"postmark_server_token", "postmark_account_token",
	"sparkpost_api_key", "sparkpost_webhook_token",
	"vonage_api_key", "vonage_api_secret",
	"nexmo_api_key", "nexmo_api_secret",
	"messagebird_api_key", "messagebird_signing_key",
	"infobip_api_key", "infobip_base_url",
	"bandwidth_account_id", "bandwidth_api_token",
	"plivo_auth_id", "plivo_auth_token",
	"aws_ses_smtp_password", "smtp_password", "smtp_user",
	"imap_password", "pop3_password",
	"push_notification_key", "apns_key", "gcm_api_key",
	"fcm_server_key", "fcm_api_key",
	"onesignal_app_id", "onesignal_api_key",
	"pusher_app_secret", "pusher_app_key",
	"ably_api_key", "ably_secret",
	"pubnub_publish_key", "pubnub_subscribe_key",
	"centrifugo_api_key", "centrifugo_token",

	// ── DevOps / CI/CD ────────────────────────────────────────────────────────
	"github_token", "github_pat", "github_actions_token",
	"gitlab_token", "gitlab_ci_token",
	"bitbucket_password", "bitbucket_token",
	"circleci_token", "travis_token", "jenkins_token",
	"drone_token", "teamcity_token",
	"sonarqube_token", "sonarcloud_token",
	"codecov_token", "coveralls_token",
	"snyk_token", "whitesource_token",
	"dependabot_token",

	// ── Monitoring / observability ────────────────────────────────────────────
	"datadog_api_key", "datadog_app_key",
	"newrelic_license_key", "newrelic_api_key",
	"sentry_dsn", "sentry_auth_token",
	"bugsnag_api_key", "rollbar_access_token",
	"honeybadger_api_key", "airbrake_project_key",
	"raygun_api_key", "loggly_token",
	"papertrail_token", "logdna_ingestion_key",
	"sumologic_access_id", "sumologic_access_key",
	"splunk_hec_token", "splunk_api_token",
	"elastic_apm_secret", "dynatrace_api_token",
	"appdynamics_account_key", "instana_agent_key",
	"prometheus_bearer_token", "grafana_api_key",
	"grafana_cloud_api_key", "victoria_metrics_token",

	// ── Analytics / marketing ─────────────────────────────────────────────────
	"mixpanel_token", "mixpanel_secret",
	"amplitude_api_key", "amplitude_secret_key",
	"segment_write_key", "segment_source_id",
	"heap_app_id", "heap_env_id",
	"fullstory_org_id", "hotjar_site_id",
	"google_analytics_id", "google_tag_manager_id",
	"facebook_pixel_id", "facebook_ads_token",
	"twitter_pixel_id", "linkedin_insight_tag",
	"tiktok_pixel_id", "snapchat_pixel_id",
	"pinterest_tag_id", "reddit_pixel_id",
	"intercom_app_id", "intercom_secret_key",
	"hubspot_api_key", "hubspot_client_secret",
	"salesforce_client_id", "salesforce_client_secret",
	"salesforce_access_token", "salesforce_refresh_token",
	"zendesk_api_token", "zendesk_oauth_token",
	"freshdesk_api_key", "freshservice_api_key",
	"jira_api_token", "confluence_api_token",
	"asana_access_token", "trello_api_key",
	"monday_api_token", "notion_api_token",
	"airtable_api_key", "airtable_pat",
	"pipedrive_api_token", "zoho_client_secret",
	"copper_api_key", "close_api_key",

	// ── Crypto / Web3 extended ────────────────────────────────────────────────
	"eth_private_key", "eth_mnemonic", "eth_keystore",
	"btc_private_key", "btc_wif", "btc_xpriv",
	"solana_private_key", "sol_keypair",
	"dot_seed", "near_private_key", "cosmos_key",
	"tron_private_key", "bnb_private_key",
	"infura_project_id", "infura_project_secret",
	"alchemy_api_key", "alchemy_auth_token",
	"moralis_api_key", "moralis_master_key",
	"quicknode_token", "ankr_api_key",
	"web3_rpc_url", "web3_provider_url",
	"contract_deployer_key", "contract_owner_key",
	"multisig_key", "cold_wallet_seed",
	"hot_wallet_key", "exchange_api_key",
	"exchange_api_secret", "exchange_passphrase",
	"okx_api_key", "okx_secret_key", "okx_passphrase",
	"bybit_api_key", "bybit_secret",
	"huobi_access_key", "huobi_secret_key",
	"kucoin_api_key", "kucoin_secret", "kucoin_passphrase",
	"bitfinex_api_key", "bitfinex_secret",
	"bitstamp_api_key", "bitstamp_secret",
	"gemini_api_key", "gemini_secret",
	"deribit_client_id", "deribit_secret",
	"paxos_api_key", "circle_api_key",
	"wbtc_key", "usdt_key", "dai_key",

	// ── Geolocation / maps ────────────────────────────────────────────────────
	"google_maps_api_key", "google_places_api_key",
	"mapbox_access_token", "mapbox_secret_token",
	"here_api_key", "here_app_id", "here_app_code",
	"tomtom_api_key", "opencage_api_key",
	"bing_maps_key", "esri_api_key",
	"foursquare_api_key", "foursquare_secret",

	// ── Shipping / logistics ──────────────────────────────────────────────────
	"fedex_account_number", "fedex_meter_number",
	"fedex_api_key", "fedex_secret_key",
	"ups_client_id", "ups_client_secret",
	"usps_user_id", "usps_password",
	"dhl_api_key", "dhl_account_number",
	"shippo_api_token", "easypost_api_key",
	"shipstation_api_key", "shipstation_secret",
	"aftership_api_key", "parcelhub_api_key",
	"aramex_account_number", "aramex_password",

	// ── AZ fintech extended ────────────────────────────────────────────────────
	"birbank_token", "birbank_api", "birbank_secret",
	"kapital_token", "kapital_api_key", "kapital_secret",
	"kapital_merchant_id", "kapital_terminal_id",
	"kapital_client_id", "kapital_client_secret",
	"birbank_client_id", "birbank_merchant_id",
	"umico_api_key", "umico_secret", "umico_token",
	"umico_client_id", "umico_client_secret",
	"umico_merchant_id", "umico_access_token",
	"pashapay_api_key", "pashapay_secret", "pashapay_merchant",
	"m10_api_key", "m10_secret", "m10_token",
	"pulpay_api_key", "pulpay_secret", "pulpay_token",
	"goldenpay_api", "goldenpay_token", "goldenpay_secret",
	"epul_api", "epul_token", "epul_merchant",
	"mpay_api", "mpay_token", "mpay_secret",
	"payriff_api", "payriff_token", "payriff_secret",
	"fido_api", "fido_token", "fido_secret",
	"portmanat_api", "portmanat_token",
	"hesab_az_key", "asanpay_key",
	"e_manat_key", "e_manat_secret",
	"kassam_api", "kassam_token", "kassam_secret",
	"smartpay_api", "smartpay_token",
	"xalqbank_api", "xalqbank_token",
	"rabitabank_api", "rabitabank_token",
	"unibank_api", "unibank_token",
	"accessbank_api", "accessbank_token",
	"expressbank_api", "expressbank_token",
	"yelobank_api", "yelobank_token",
	"vtb_az_api", "vtb_az_token",
	"abb_api_key", "abb_token", "abb_secret",
	"ibar_token", "ibar_api", "ibar_secret",
	"pasha_api_key", "pasha_token", "pasha_secret",
	"leobank_api", "leobank_token",
	"afb_api_key", "afb_token", "afb_secret",
	"amrahbank_api", "amrahbank_token",
	"demirbank_api", "demirbank_token",
	"kredobank_api", "kredobank_token",
	"atabank_api", "atabank_token",
	"ziraatbank_api", "ziraatbank_token",
	"turanbank_api", "turanbank_token",
	"azercell_api_key", "azercell_token", "azercell_secret",
	"bakcell_api_key", "bakcell_token", "bakcell_secret",
	"nar_api_key", "nar_token", "nar_secret",
	"socar_api_key", "socar_token", "socar_secret",
	"bakikart_token", "bakikart_api",
	"metro_token", "metro_api", "metro_secret",
	"iticket_token", "iticket_api", "iticket_secret",
	"egov_token", "egov_api", "egov_secret",
	"mygov_token", "mygov_api",
	"asan_imza_key", "asan_imza_token",
	"e_sosial_token", "e_sosial_api",
	"gomruk_token", "gomruk_api",
	"vergiler_token", "vergiler_api",
	"voen", "fin_kod", "az_fin",
	"azal_api", "azal_token", "azal_secret",
	"wolt_api", "wolt_token",
	"bolt_api", "bolt_token",
	"kontakt_api", "kontakt_token",
	"trendyol_api", "trendyol_token",
	"alinino_api", "alinino_token",
	"baku_electronics_api",
	"irshad_api", "irshad_token",
	"colibri_api", "colibri_token",
	"kango_api", "kango_token",
	"mova_api", "mova_token",
	"swift_bic_az", "sepa_az",
	"rtgs_az", "ach_az",
	"cbar_rate", "cbar_api",
	"nba_az_key",
	"azerpoct_api", "azerpoct_token",
	"dhl_az_api", "fedex_az_api", "ups_az_api",
	"starex_api", "camex_api",
	"park_cinema_api", "cinema_plus_api",
	"iticket_client", "cinemastercard_api",
}

func GetBankingKeywordRegex() string {
	return `(?i)\b(` + strings.Join(BankingKeywordList, "|") + `)\b\s*[:=]\s*['"]([^'"]{4,80})['"]`
}
